=== bata26/MobilityBehaviour/production_system/json/schemas/message-configuration-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "src": {
            "type" : "object",
            "properties": {
                "ip" : {
                    "type" : "string"
                },
                "port" : {
                    "type" : "integer"
                }
            },
            "required": ["port" , "ip"]
        },
        "evaluation-system": {
            "type" : "object",
            "properties": {
                "ip" : {
                    "type" : "string"
                },
                "port" : {
                    "type" : "integer"
                }
            },
            "required": ["port" , "ip"]
        },
        "client-system": {
            "type" : "object",
            "properties": {
                "ip" : {
                    "type" : "string"
                },
                "port" : {
                    "type" : "integer"
                }
            },
            "required": ["port" , "ip"]
        },
        "messaging-system": {
            "type" : "object",
            "properties": {
                "ip" : {
                    "type" : "string"
                },
                "port" : {
                    "type" : "integer"
                }
            },
            "required": ["port" , "ip"]        
        }
    },
    "required" : ["src" , "evaluation-system" , "client-system" , "messaging-system"]

}

=== bata26/MobilityBehaviour/production_system/json/message-configuration.json
{
    "src" : {
        "ip" : "0.0.0.0",
        "port" : 6001
    },
    "evaluation-system":{
        "ip" : "10.8.0.7",
        "port" : 6000
    },
    "client-system":{
        "ip" : "172.23.0.0",
        "port" : 6000
    },
    "messaging-system":{
        "ip" : "172.23.0.0",
        "port" : 6000
    }
}
